name: E2E Tests
on:
  pull_request:
    branches:
      - main
permissions:
  contents: read
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
        with:
          version: 10
      - uses: actions/setup-node@v3
        with:
          node-version: "23.x"
          registry-url: "https://registry.npmjs.org"
      - run: pnpm install --frozen-lockfile
      - run: pnpm -r build

      - name: Install Playwright
        run: pnpm exec playwright install

      - name: Run E2E Tests
        run: pnpm playwright test --reporter=html --trace on

      - uses: ryand56/r2-upload-action@latest # Can be any release
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.R2_BUCKET }}
          source-dir: playwright-report
          destination-dir: "run-${{ github.run_id }}-${{ github.run_attempt }}"
          output-file-url: true # defaults to true
          multipart-size: 100 # If the file size is greater than the value provided here, then use multipart upload
          max-retries: 5 # The maximum number of retries it takes to upload a multipart chunk until it moves on to the next part
          multipart-concurrent: true # Whether to concurrently upload a multipart chunk
          keep-file-fresh: false # defaults to false

      - name: Leave PR comment with test results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const comment = `## E2E Test Results
            [View the test results](https://playwright.orange-js.dev/run-${{ github.run_id }}-${{ github.run_attempt }}/index.html)`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
