#
# Creates 0.0.0-$COMMIT versions for every package and publishes them to NPM
#
name: Publish preleases to NPM
on:
  pull_request:
    branches:
      - main
permissions:
  contents: read
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
        with:
          version: 10
      - uses: actions/setup-node@v3
        with:
          node-version: "23.x"
          registry-url: "https://registry.npmjs.org"
      - run: pnpm install --frozen-lockfile
      - run: pnpm -r build
      - name: Write dev versions
        env:
          PR_SHA: ${{ github.event.pull_request.head.sha }}
        run: node scripts/version-for-prerelease.ts

      - name: Publish core
        run: pnpm publish --no-git-checks --tag dev
        working-directory: packages/core
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish vite
        run: pnpm publish --no-git-checks --tag dev
        working-directory: packages/vite
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish create-orange
        run: pnpm publish --no-git-checks --tag dev
        working-directory: packages/create-orange
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish cli
        run: pnpm publish --no-git-checks --tag dev
        working-directory: packages/cli
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Leave PR comment with install instructions
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const sha = context.payload.pull_request.head.sha.substring(0, 7);
            const comment = `## Prerelease Packages Available

            Install the prerelease packages with:
            \`\`\`bash
            npm install @orange-js/orange@0.0.0-${sha} && npm install -D @orange-js/vite@0.0.0-${sha}
            pnpm add @orange-js/orange@0.0.0-${sha} && pnpm add -D @orange-js/vite@0.0.0-${sha}
            yarn add @orange-js/orange@0.0.0-${sha} && yarn add -D @orange-js/vite@0.0.0-${sha}
            bun add @orange-js/orange@0.0.0-${sha} && bun add -D @orange-js/vite@0.0.0-${sha}
            \`\`\``;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
